
TOP_ENTITY = emif16_avmm_bridge_tb

vpath %.sv ../../tb ../../rtl
HDL_SRC = emif16_avmm_bridge.sv \
          emif16_avmm_bridge_tb.sv \
          emif16_model.sv

include ../../scripts/makefiles/modelsim/modelsim.mk
